### PR TITLE
Feature/reverse rec

### PR DESCRIPTION
**Pull request by sontags**
@resmo OK?

### CODE REVIEW

**Comment by niwo** [comment]
You may also take a look at https://github.com/digitalocean/netbox
If enhanced with netmgmt scanning and reservation features it would be perfect ;-)

**Comment by resmo** [comment]
@niwo Thanks for the hint, looks perfect for a new infras

**Comment by sontags** [comment]
@niwo I would love to contribute to netbox, but at the moment I have no time on hand for a complete go rewrite.

**Comment by onitake** [comment]
Code LGTM.
PTR records are useful.
@gildegoma Let's merge, deploy and test it.

**Review by onitake — APPROVED** [review]

**Comment by resmo** [comment]
yeay, blast from the past, hello everyone ;)

**Comment by onitake** [comment]
@resmo :wave: Somehow everybody forgot about this feature PR...

**Comment by sontags** [comment]
Hello all 👋!

You guys are still using this 🤨...

**Comment by onitake** [comment]
Hi @sontags - kind of.
We're looking into replacements though. :wink: 
How are you by the way?

**Comment by sontags** [comment]
The replacement is called DHCP. Appears to work quite well.

I am good, how are things at swisstxt?

**Comment by onitake** [comment]
> The replacement is called DHCP. Appears to work quite well.

Things are often much more complicated than the obvious solution... :smile: 

> I am good, how are things at swisstxt?

A bit chaotic, same old and a ton of new stuff. In other words: Business as usual.
Cargo is getting really popular, we just released version 3.0.0!

**Comment by gildegoma** [comment]
Hi everyone :-)

Merging... and we'll see if it lands to run somewhere.

**Comment by resmo** [comment]
:wave:

**Comment by sontags** [comment]
Salut Gilles! Happy to see this PR merged!

**Pull request merged**
